services:
  controller:
    image: pmman/link42:latest
    build:
      context: ..
      dockerfile: Dockerfile.controller
    volumes:
      - link42-runtime:/link42
    environment:
      LINK42_DATABASE_URL: sqlite:////link42/data/link42.db
      LINK42_CONFIG_DIR: /link42/config
      LINK42_WEB_DIST_DIR: /opt/link42/web
    ports:
      - "8000:8000"

volumes:
  link42-runtime:
